### ISSUE TITLE
openwrt路由器的校园网自动登录

### ISSUE THREAD

**Issue by HeZi930** [LLinVIP/live_new#4]
您好，我之前写了一篇关于如何在 OpenWrt 路由器上实现哆点 Drcom 校园网 WEB 自动登录的文章：[关于 openwrt 路由器及哆点 Drcom 校园网 WEB 自动登录](https://hezi930.github.io/2024/06/03/%E5%85%B3%E4%BA%8Eopenwrt%E8%B7%AF%E7%94%B1%E5%99%A8%E5%8F%8A%E5%93%86%E7%82%B9Drcom%E6%A0%A1%E5%9B%AD%E7%BD%91WEB%E8%87%AA%E5%8A%A8%E7%99%BB%E5%BD%95/)。我觉得这篇文章可能对其他使用路由器的用户有帮助，因此希望您可以考虑将它加入到[网络在矿大&一体化网络&手机卡](https://live.cumt.asia/Life/Network/IntegratedNetwork.html)页面中的**使用路由器**标题下。

**Comment by LLinVIP** [comment]
好的，我去看一下

**Comment by LLinVIP** [comment]
感谢您的建议，将会在下一版上更新。之前我还写过一个py版的来着，找不到了😂

**Comment by LLinVIP** [comment]
已更新
